OS: OSX
osx_image: xcode12.3
language: swift
script: 
  - xcodebuild clean build test  -workspace EssentialWorkspace.xcworkspace -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
  - xcodebuild clean build test  -workspace EssentialWorkspace.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.4,name=iPhone 12" ONLY_ACTIVE_ARCH=YES